"""
inference.py  —  SHADOW_REGISTER Inference Script (Submission-Ready)
=====================================================================
Runs a single episode of SHADOW_REGISTER using an OpenAI-compatible LLM
via the OpenEnv async SDK (Docker-managed environment).

Emits strictly formatted [START] / [STEP] / [END] logs to stdout so the
automated evaluator can parse scores without regex fragility.

Required environment variables
-------------------------------
    IMAGE_NAME     Docker image name injected by the evaluation platform
    API_BASE_URL   LLM API base URL  (e.g. https://api.openai.com/v1)
    MODEL_NAME     Model identifier  (e.g. gpt-4o)
    HF_TOKEN       Hugging Face / API key

Usage
-----
    python inference.py                          # default: noisy_entry, seed=42
    python inference.py --task timestomp_proxy --seed 7
    python inference.py --task stealthy_persistence --max-steps 40
"""

from __future__ import annotations

import argparse
import ast
import asyncio
import json
import os
import re
import sys
from typing import Any, Dict, List, Optional

from openai import OpenAI

# Import the OpenEnv SDK generated by `openenv init`
from shadow_register import ShadowRegisterAction, ShadowRegisterEnv

# ---------------------------------------------------------------------------
# Config from environment
# ---------------------------------------------------------------------------

IMAGE_NAME:   str = os.environ.get("IMAGE_NAME", "")          # injected by platform
API_BASE_URL: str = os.environ.get("API_BASE_URL", "https://router.huggingface.co/v1")
MODEL_NAME:   str = os.environ.get("MODEL_NAME",   "gpt-4o")
API_KEY:      str = os.environ.get("HF_TOKEN",     "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")

TEMPERATURE:  float = 0.0
MAX_TOKENS:   int   = 1024
MAX_STEPS:    int   = 40
MAX_TOTAL_REWARD: float = 1.0
SUCCESS_SCORE_THRESHOLD: float = 0.80

BENCHMARK = "shadow_register"

# ---------------------------------------------------------------------------
# Structured stdout logging  — literal string format required by evaluator
# ---------------------------------------------------------------------------

def log_start(task: str, env: str, model: str) -> None:
    print(f"[START] task={task} env={env} model={model}", flush=True)


def log_step(step: int, action: str, reward: float, done: bool, error: Optional[str]) -> None:
    error_val = error if error else "null"
    done_val  = str(done).lower()
    print(
        f"[STEP] step={step} action={action} reward={reward:.2f} done={done_val} error={error_val}",
        flush=True,
    )


def log_end(success: bool, steps: int, score: float, rewards: List[float]) -> None:
    rewards_str = ",".join(f"{r:.2f}" for r in rewards)
    print(
        f"[END] success={str(success).lower()} steps={steps} score={score:.3f} rewards={rewards_str}",
        flush=True,
    )


# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are an expert Digital Forensics & Incident Response (DFIR) analyst \
operating a terminal on a compromised Linux server.

Your goal is to reconstruct the attacker's Kill Chain and file a case report \
using SubmitCase.

AVAILABLE COMMANDS
──────────────────
Search  {"action": "Search",  "query": "<keyword>"}
Inspect {"action": "Inspect", "path":  "<absolute/path>"}
Read    {"action": "Read",    "path":  "<absolute/path>", "offset": <int>}
Tag     {"action": "Tag",     "label": "<key>",           "value": "<evidence>"}
SubmitCase {
  "action": "SubmitCase",
  "pivots": [
    {
      "artifact": "<path>",
      "ioc":      "<value>",
      "type":     "NETWORK_IP|EVENT_TIMESTAMP|PATH_TO_FILE|COMMAND_STRING|USER_ACCOUNT|FILE_HASH",
      "reason":   "<brief explanation>"
    }
  ]
}

RULES
─────
• Every action costs 1 budget unit (max 50). Budget = 0 → episode ends.
• Search returns filenames + hit counts only — NOT file content.
• Read returns a 1000-character window. Use offset to page through large files.
• Inspect returns stat metadata (mtime / atime / ctime / size / permissions).
• Tag records evidence for your own reference. Use it to track findings.
• SubmitCase ends the episode immediately. Only call it when confident.
• Some files are HONEYPOTS. Tagging them penalises your score heavily.
• Respond with EXACTLY ONE JSON action object and nothing else.
"""


# ---------------------------------------------------------------------------
# Model call
# ---------------------------------------------------------------------------

def get_model_action(
    client:       OpenAI,
    step:         int,
    current_view: str,
    last_reward:  float,
    history:      List[str],
) -> Dict[str, Any]:
    """
    Ask the LLM for the next ForensicAction.
    Returns a parsed dict or a fallback Search action on failure.
    """
    history_block = "\n".join(history[-10:]) if history else "(none)"

    user_msg = (
        f"=== Step {step} ===\n"
        f"Budget consumed: {step - 1} / 40\n"
        f"Last reward: {last_reward:+.3f}\n\n"
        f"Recent history:\n{history_block}\n\n"
        f"Current terminal output:\n{current_view}\n\n"
        f"Issue your next command as a single JSON object."
    )

    try:
        completion = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": user_msg},
            ],
            temperature=TEMPERATURE,
            max_tokens=MAX_TOKENS,
            stream=False,
        )
        raw = (completion.choices[0].message.content or "").strip()
        return _parse_action(raw)
    except Exception as exc:
        print(f"[DEBUG] Model call failed: {exc}", flush=True)
        return {"action": "Search", "query": "failed"}


def _parse_action(raw: str) -> Dict[str, Any]:
    """
    Extract the first JSON object from the model's response.
    Handles markdown fences, stray prose, and single-quote JSON.
    """
    # Strip markdown fences
    raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()

    # Try direct parse first
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass

    # Extract first {...} block
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        candidate = match.group(0)
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
        # Last resort: ast.literal_eval for single-quoted dicts
        try:
            result = ast.literal_eval(candidate)
            if isinstance(result, dict):
                return result
        except Exception:
            pass

    # Absolute fallback
    print(f"[DEBUG] Could not parse model output: {raw[:200]}", flush=True)
    return {"action": "Search", "query": "log"}


# ---------------------------------------------------------------------------
# Main loop  — async, Docker-managed environment via OpenEnv SDK
# ---------------------------------------------------------------------------

async def main(task: str, seed: int, max_steps: int) -> None:
    client_llm = OpenAI(base_url=API_BASE_URL, api_key=API_KEY)

    # Spin up environment from the Docker image injected by the platform
    env = await ShadowRegisterEnv.from_docker_image(IMAGE_NAME)

    history:     List[str]   = []
    rewards:     List[float] = []
    steps_taken: int         = 0
    score:       float       = 0.0
    success:     bool        = False

    log_start(task=task, env=BENCHMARK, model=MODEL_NAME)

    try:
        # ── reset ─────────────────────────────────────────────────────
        result      = await env.reset(task=task, seed=seed)
        last_view   = result.observation.current_view
        last_reward = 0.0

        for step in range(1, max_steps + 1):
            if result.done:
                break

            # ── model decision ────────────────────────────────────────
            action_dict = get_model_action(
                client_llm,
                step=step,
                current_view=last_view,
                last_reward=last_reward,
                history=history,
            )

            # Compact string for the [STEP] log line
            action_str = json.dumps(action_dict, separators=(",", ":"))

            # ── environment step ──────────────────────────────────────
            try:
                result      = await env.step(ShadowRegisterAction(**action_dict))
                reward      = float(result.reward or 0.0)
                done        = bool(result.done)
                error       = None
                last_view   = result.observation.current_view
                last_reward = reward
            except Exception as exc:
                reward = 0.0
                done   = False
                error  = str(exc)
                print(f"[DEBUG] Step {step} error: {exc}", flush=True)

            rewards.append(reward)
            steps_taken = step

            log_step(step=step, action=action_str, reward=reward, done=done, error=error)

            history.append(
                f"Step {step}: {action_dict.get('action', '?')} → reward {reward:+.3f}"
            )

            if done:
                # Pull grader score if the SDK exposes it
                grader = getattr(result, "grader_report", None)
                if grader:
                    score   = float(grader.get("score", 0.0))
                    success = score >= SUCCESS_SCORE_THRESHOLD
                    print(f"[DEBUG] Grader verdict: {grader.get('verdict')}", flush=True)
                break

        # Fallback normalisation if no grader report was attached
        if not success and rewards:
            score   = min(max(sum(rewards) / MAX_TOTAL_REWARD, 0.0), 1.0)
            success = score >= SUCCESS_SCORE_THRESHOLD

    finally:
        try:
            await env.close()
        except Exception as e:
            print(f"[DEBUG] env.close() error (container cleanup): {e}", flush=True)

        log_end(success=success, steps=steps_taken, score=score, rewards=rewards)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="SHADOW_REGISTER submission inference script"
    )
    parser.add_argument(
        "--task",
        default="noisy_entry",
        choices=["noisy_entry", "stealthy_persistence", "timestomp_proxy"],
        help="Which scenario to run (default: noisy_entry)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="World-generation seed (default: 42)",
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=MAX_STEPS,
        help=f"Max steps before forced termination (default: {MAX_STEPS})",
    )
    args = parser.parse_args()

    asyncio.run(main(task=args.task, seed=args.seed, max_steps=args.max_steps))